### ISSUE TITLE
feat: disable boundaries check

### ISSUE THREAD

**Issue by jbflo** [fkhadra/react-contexify#217] opened 2022-09-01 13:30 UTC
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When the menu Height is > to window Height the menu top position  top goes off-screen 
and you can't see some item 

      if (_y + menuHeight > windowHeight) {
        _y -= _y + menuHeight - windowHeight;
      }
I would wonder why this minus , cause it cause problem when the menu has a lot of item. 
it loose the fix position 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. :**

Just add a lot of item to your Menu , as much as to make the menu height > to the window screen 
to have the scroll bar.

**What is the expected behavior?**
Menu position should preserve the fix position 

the Hook function to set the State position i would say it is not necessary or should be updated 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
React 16.*
Chrome , Opera, Firefox

**Comment by fkhadra** [comment] 2022-11-03 19:28
Actually, this is by design, the position is recomputed using to prevent the menu for going outside the window. I'll add an option to disable the behavior in the next release

**Comment by fkhadra** [comment] 2022-11-03 21:52
Fixed by https://github.com/fkhadra/react-contexify/pull/220

**Closed** 2022-11-13 22:09 UTC
Labels: fixed in next release
